### ISSUE TITLE
Credit.

### ISSUE THREAD

**Issue by Habbolant** [ilouHD/FFA#1]
Thanks for using my ItemBuilder, but please give credit.

**Comment by ilouHD** [comment]
I don't know why you think it's your ItemBuilder. I wrote it my own for a project and improved it for Mivcon :)

**Comment by Habbolant** [comment]
You skidded my code and made it even worse. Great "improving".

**Comment by ilouHD** [comment]
When it's your ItemBuilder, why do I wrote my version month before you wrote your ItemBuilder? It doesn't make sense.

**Comment by Habbolant** [comment]
If you wrote your ItemBuilder before mine, why is it almost the exact same code as one of my early versions? Doesn't make sense either.

**Comment by ilouHD** [comment]
Eventually you stole it from me o.O.

**Comment by Habbolant** [comment]
Sure.

**Comment by Habbolant** [comment]
Can you please tell me again, when did you write "your" ItemBuilder?
